### PR TITLE
Update stylelint-order.

### PR DESCRIPTION
**Pull request by satazor**
See: https://github.com/suitcss/stylelint-config-suitcss/issues/28

### CODE REVIEW

**Comment by jeddy3** [comment]
@satazor Thanks! 

For some reason I was no longer watching this repo and so missed your issue and PR. Sorry about the delay merging your it. I'll get a release out now.

**Comment by simonsmith** [comment]
Whoops, forgot this. Thanks @satazor!

@jeddy3 What kind of release would this be semver wise?

**Comment by jeddy3** [comment]
@simonsmith I was going to with major as someone might have overridden the `order/declaration-block-properties-alphabetical-order` rule when extending the config, and because of a rule name change this could break their builds.

**Comment by simonsmith** [comment]
Great, I was thinking the same :)

**Comment by satazor** [comment]
@jeddy3 no problem and ty very much

**Pull request merged**
